import hashlib
import hmac
import logging
import re

from werkzeug.utils import redirect

from odoo import http
from odoo.http import request

_logger = logging.getLogger(__name__)

# Reference format: LAD_ prefix followed by alphanumeric/underscore
_REFERENCE_RE = re.compile(r'^LAD_[A-Za-z0-9_]+$')


class EPSBayernController(http.Controller):
    _return_url = '/payment/epsbayern/return'

    @staticmethod
    def _compute_return_hmac(reference, db_secret):
        """Compute HMAC-SHA256 signature for the return URL."""
        return hmac.new(
            db_secret.encode(),
            reference.encode(),
            hashlib.sha256
        ).hexdigest()[:32]

    @http.route(_return_url, type='http', auth='public', methods=['GET', 'POST'], csrf=False)
    def payment_return(self, **kwargs):
        """Handle the redirect back from the EPS Bayern paypage after payment."""
        _logger.info("EPS Bayern return with data: %s", kwargs)

        reference = kwargs.get('reference')
        eps_txnid = kwargs.get('txnid')  # on return from payment, it gives txnid in query param
        signature = kwargs.get('sig')

        if not reference:
            _logger.error("EPS Bayern return: missing reference parameter")
            return redirect('/payment/status')

        # Validate reference format to prevent abuse
        if not _REFERENCE_RE.match(reference):
            _logger.error("EPS Bayern return: invalid reference format: %s", reference)
            return redirect('/payment/status')

        # Verify HMAC signature to ensure the return URL was generated by us
        db_secret = request.env['ir.config_parameter'].sudo().get_param('database.secret')
        expected_sig = self._compute_return_hmac(reference, db_secret)
        if not signature or not hmac.compare_digest(signature, expected_sig):
            _logger.error("EPS Bayern return: invalid or missing signature for reference %s", reference)
            return redirect('/payment/status')

        notification_data = {'reference': reference, 'eps_txnid': eps_txnid}
        request.env['payment.transaction'].sudo()._handle_notification_data(
            'epsbayern', notification_data
        )

        return redirect('/payment/status')